### ISSUE TITLE
[feat:]Add a Map showing all the locations where the link get clicked

### ISSUE THREAD

**Issue by BiswajitSahoo-tech** [TheRedstoneRadiant/Qurl.gq#18]
Hi @TheRedstoneRadiant 
I want to add a Map pointing to all link-accessed locations on the `/info` page below the IP address table
Thank You

**Comment by BiswajitSahoo-tech** [comment]
Please assign this to me
Thanks

**Comment by TheRedstoneRadiant** [comment]
This is a great idea! 

Feel free to create a pull request with your implementation.
