### ISSUE TITLE
Create format script

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [TheRedstoneRadiant/Qurl.gq#24]
TODO: Add a script in `package.json` to format every file (*.js, *.ejs, *.css).

Feel free to use any npm library as a devDependancy.

**Comment by anshul137** [comment]
I can help you with this issue.

**Comment by anshul137** [comment]
Send the [PR](https://github.com/TheRedstoneRadiant/Qurl.gq/pull/30)
