### ISSUE TITLE
Infinite custom URL redirect

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [TheRedstoneRadiant/Qurl.gq#37]
You can redirect a URL to itself, see:
https://qurl.gq/hello
https://qurl.gq/hello/info
![image](https://user-images.githubusercontent.com/76220359/210470134-41938a6d-5296-49f3-a115-d3b258aefc59.png)

**Comment by TheRedstoneRadiant** [comment]
@eesazahed

**Comment by eesazahed** [comment]
@TheRedstoneRadiant #38 complete
