### ISSUE TITLE
Handle DB not connected scenario

### ISSUE THREAD

**Issue by westerandr** [TheRedstoneRadiant/Qurl.gq#5]
Hi there, how would you like to handle the situation where a user visits Qurl.gq but the MongoDB instance is not able to connect.

a. Stop NodeJS Server?
b. Allow the server to still run but provide client with feedback that a DB issue is being experienced and to check back later?

Upon your answer, can I be assigned this issue please?

Thank you for reading this issue.

**Comment by TheRedstoneRadiant** [comment]
Hello!

I'd prefer the first option, since it's easier for the user to understand that the application is offline, as opposed to an error message.

Yes, feel free to go ahead and write an implementation!

Thank you <3
