### ISSUE TITLE
404 Page rendered with invalid status code

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [TheRedstoneRadiant/Qurl.gq#9]
In [router/index.js](https://github.com/TheRedstoneRadiant/Qurl.gq/blob/main/router/index.js) the 404 page is rendered with the incorrect status code.

404 Page: https://qurl.gq/404

This can lead to issues during development.

**Comment by TheRedstoneRadiant** [comment]
Assigned!

Feel free to create a pull request with your solution.

**Comment by Aman0307** [comment]
@TheRedstoneRadiant  can you please explain what the issue is?? Also how can I reproduce the issue??

**Comment by TheRedstoneRadiant** [comment]
When visiting the [404](https://qurl.gq/404) page, the webserver returns status code 200 instead of 404.
